### ISSUE TITLE
Improve build performance

### ISSUE THREAD

**Issue by rymsha** [enonic/npm-react4xp#232]
```
- `enonic project gradle deploy -Pdev`

- - `npm explore @enonic/react4xp -- npm run build:react4xp`

- - - `npm run tsup:client && npm run webpack:components && npm run tsup:executor && npm run webpack:globals && npm run webpack:nashornPolyfills`
- - - -  `@enonic/react4xp@4.0.0-B6 tsup:client`
- - - - `@enonic/react4xp@4.0.0-B6 webpack:components`
- - - - `@enonic/react4xp@4.0.0-B6 tsup:executor`
- - - - ` @enonic/react4xp@4.0.0-B6 webpack:globals`
- - - - `@enonic/react4xp@4.0.0-B6 webpack:nashornPolyfills` 
```

`tsup:client` and `tsup:executor` are "always" the same. But we still take up 17ms each + 1-3 seconds each to start node each time. merging it into one tsup would save 1-3 seconds.

`webpack:globals` `webpack:nashornPolyfills` are very stable. may be _slow_ (depends on what developer put into globals and polyfills ) + 1-3 seconds each to start node each time. We should make it one process to save 1-3 seconds and cache via webpack.

`webpack:components` is the most dynamic one and slowest one, and we already document how to cache it. All good here.

**Comment by ComLock** [comment]
There are multiple solutions:

1. Run in parallell (in terminal) so startup cost, and work time, isn't the sum of everything, but only the sum of the slowest one. (caching complexity++)
(the rest are not parallell via the terminal, but might be in parallell by the build tool, if it supports it)
2. Use webpack for everything (still slow)
3. Use tsup for everything (fast, but not a tool people out there is familiar with yet)

Personally I would go for solution 3.
